Step 1-2 ViewModelの導入
hamadayuuki/zozo-ios-engineer-codecheck pull request #6
Opened 2024-06-25 03:27 UTC by hamadayuuki

## 概要(一言で簡潔に)

APIClient 呼び出し用のView(APIClientViewController.swift) に対応するViewModelを作成し、状態管理を可能にした。

## 詳細

現状VCのもつ状態は **isLoading** のみである。
そのため、ViewModelの実装自体はisLoadingが変わると背景色が変化するだけの簡単なものになっている。

※ APIClient や Buttonアニメーション 等の実装は別PR

## 確認してほしい点

- Viewでの状態変更がメインスレッド上で行われているか
- View-ViewModelのデータフローは適切か

## UI

| "GET"ボタンを押した時の挙動 |
| --- |
| <img width = 300 src = "https://github.com/hamadayuuki/zozo-ios-engineer-codecheck/assets/55442055/073e4ed8-4421-4dff-8302-5d52650d3da5"> |

## 参考

2024-06-27 03:07 UTC, nwatabou commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +        setupLayout()
ここのメソッド呼び出しの順番を逆にするとクラッシュしちゃいそうな気がするので、
`configureViews()` みたいなメソッドを用意し、その中でまとめてやっちゃうと良さそうに思いました！

2024-06-28 00:55 UTC, hamadayuuki commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +        )
lazy 使ってインスタンス化されるタイミングずらす方がスマートだと思ったので修正しました！ [5dd1f95](https://github.com/hamadayuuki/zozo-ios-engineer-codecheck/pull/6/commits/5dd1f95f52092e29fb1a3d512197600321933bf0)

2024-06-28 00:56 UTC, hamadayuuki commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +                }
対応しました！ [ba36b3b](https://github.com/hamadayuuki/zozo-ios-engineer-codecheck/pull/6/commits/ba36b3b534d0b87a6574bb1be3772651cf2b8062)

2024-06-28 01:05 UTC, hamadayuuki commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +    private let viewModel: APIClientViewModel = .init()
テスタブルにするため、以下2点対応しました！

**1. init() で定義しViewModelのDI可能に**

**2. VM の抽象化**

以下に示すように、`VMProtocol = InputProtocol+OutputProtocol` としてVMを抽象化しています。
コメントいただく前は、Input,Output のみの抽象化で十分だと思っていましたが、他のファイルでProtocolを呼び出す際 Input,Outputを毎回呼び出すのはヒューマンエラーの元になりかねないなと思ったので、VMとしてInput,Outputまとめて抽象化しています。
また、他のファイルから呼び出されることを考慮し、protocolのアクセスレベルをprivateから変更しています。

```APIClientViewModel.swift
protocol APIClientViewModelProtocol: APIClientViewModelInput, APIClientViewModelInputOutput {}
```

2024-06-28 01:12 UTC, hamadayuuki commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +        setupLayout()
対応しました！[af34995](https://github.com/hamadayuuki/zozo-ios-engineer-codecheck/pull/6/commits/af34995b74b1635b7877cc762e430cced4803df2)

Viewへのコンポーネントを追加(`addSubViews()`) と コンポーネントのレイアウト(`setupLayout()`) 
以上2つの責務分けを目的としてメソッドを分けて定義していましたが、今回の実装ではコード量も少なく責務分けする必要性がないので、`configureViews() `にまとめたいと思います！

2024-06-28 01:18 UTC, hamadayuuki commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +        setupLayout()
@nwatabou 
今後、UI実装のコード量が多くなった場合はUI実装を上記コメントに示した理由から(当初のPRのように)2つのメソッドに定義しようかなと思うのですが、どうでしょうか？

責務分けするより、メソッド呼び出しの順番を逆に"できてしまう"設計自体が問題である場合は `configureViews() `にまとめようかなと思います！

2024-06-28 07:55 UTC, Ogijun2018 requested changes

2024-06-28 07:55 UTC, Ogijun2018 commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +    // MARK: - UI compornents
めちゃくちゃ細かいtypoだけど
```suggestion
    // MARK: - UI components
```

2024-06-28 07:56 UTC, Ogijun2018 commented on zozo-ios-engineer-codecheck/APIClientViewModel.swift
> +}
ここらへんの設計考えてるのすごい

2024-06-28 07:57 UTC, Ogijun2018 commented
自分のレビューはOptionalな感じに思ってもらって大丈夫なので、基本はとしさん（+なんしーさん？）のApproveがあればマージしてもらって大丈夫っす 🙆‍♂️

2024-07-01 02:29 UTC, hamadayuuki commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +    // MARK: - UI compornents
ありがとうございます！
修正しました！ [6a7d22f](https://github.com/hamadayuuki/zozo-ios-engineer-codecheck/pull/6/commits/6a7d22fdc2657a62bcf5a203320f4d40ab9e5ed9)

2024-07-01 02:34 UTC, tosh7 approved these changes

2024-07-01 02:39 UTC, Ogijun2018 commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +    private let viewModel: APIClientViewModel
（nits） `APIClientVC/VM` という命名がちょっと気になったかもしれないです。
今の所API叩くボタンあるだけの画面なので問題なさそうだけど、今後ここはGitHubのリポジトリを検索する画面（アプリとしてはホームに当たる）になると思うので、どこかのタイミングでVC/VM名に変更入りそうだなと思い。

2024-07-01 02:40 UTC, Ogijun2018 approved these changes
指摘に対応するかどうかはお任せします！

2024-07-01 02:45 UTC, hamadayuuki commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +    private let viewModel: APIClientViewModel
コメントありがとうございます！
今後のPR(APIClient実装後の VCとAPIClientの繋ぎ込み)にて命名変更する予定でした。(コメントに書いておけばよかったですね... mm)

おっしゃる通りで、僕も`APIClient~~` という命名は不適切だという認識です。
しかし、課題の内容から VCを作る目的を **APIClinet実装のため** だと判断したので、本PRでは`APIClient~~`でレビューお願いしています！
今後のPRで対応していきます！

2024-07-02 00:47 UTC, nwatabou commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +        setupLayout()
> メソッド呼び出しの順番を逆に"できてしまう"設計自体が問題

ZOZOTOWN iOS チーム内では特に規則として明言はされていませんが、個人的にはメソッドの呼び出し順番を逆にすることで破綻する設計はできるだけ避けたい気持ちですね、、、！

メソッドを分けるのであれば、順番があることをコメントで補足するなりして「必ずこの順番で呼び出す必要があること」というのを明確にしておきたいです！

2024-07-02 00:48 UTC, nwatabou approved these changes
![LGTM](https://image.lgtmoon.dev/253702)

2024-07-02 01:35 UTC, Ogijun2018 commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +    private let viewModel: APIClientViewModel
了解です！よろしく ✋

2024-07-02 02:24 UTC, hamadayuuki commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +        setupLayout()
了解です！
改めてTOWNのコード等見てみると、メソッド分けない方が設計として良いと思いました！ 笑
今後は メソッド分けない を優先度高くしつつ、可読性が下がるようなら別途対応していきます...

2024-07-02 02:24 UTC, merged

2025-05-15 04:46 UTC, hamadayuuki commented on zozo-ios-engineer-codecheck/APIClientViewController.swift
> +    }
新卒教育プラン_Combineの読み書き