リポジトリ検索画面をブラッシュアップ
hamadayuuki/zozo-ios-engineer-codecheck pull request #9
Opened 2024-08-06 03:31 UTC by hamadayuuki

2024-08-06 08:40 UTC, hamadayuuki commented on zozo-ios-engineer-codecheck/Data/Response/SearchRepositoriesResponse.swift
> +    var language: String?
GithubAPIからのレスポンスに合わせて修正しました。

2024-08-06 09:53 UTC, hamadayuuki commented on zozo-ios-engineer-codecheck/Feature/SearchRepository/SearchRepositoryViewController.swift
> +    private func resetDataSource() {
リストを初期化するために呼び出します。

2024-08-15 08:53 UTC, tosh7 requested changes
```
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<SnapKit.LayoutConstraint:0x60000263b120@RepositoryViewCell.swift#77 UIStackView:0x105145670.top == UIView:0x105145820.top + 12.0>",
    "<SnapKit.LayoutConstraint:0x600002638e40@RepositoryViewCell.swift#77 UIStackView:0x105145670.bottom == UIView:0x105145820.bottom - 12.0>",
    "<NSLayoutConstraint:0x6000021794a0 'UIView-Encapsulated-Layout-Height' UIView:0x105145820.height == 1   (active)>"
)

Will attempt to recover by breaking constraint 
<SnapKit.LayoutConstraint:0x600002638e40@RepositoryViewCell.swift#77 UIStackView:0x105145670.bottom == UIView:0x105145820.bottom - 12.0>
```

ランタイムでconsole見てみると、制約が壊れているかも

2025-05-02 06:54 UTC, hamadayuuki commented
> ```
> Unable to simultaneously satisfy constraints.
> 	Probably at least one of the constraints in the following list is one you don't want. 
> 	Try this: 
> 		(1) look at each constraint and try to figure out which you don't expect; 
> 		(2) find the code that added the unwanted constraint or constraints and fix it. 
> (
>     "<SnapKit.LayoutConstraint:0x60000263b120@RepositoryViewCell.swift#77 UIStackView:0x105145670.top == UIView:0x105145820.top + 12.0>",
>     "<SnapKit.LayoutConstraint:0x600002638e40@RepositoryViewCell.swift#77 UIStackView:0x105145670.bottom == UIView:0x105145820.bottom - 12.0>",
>     "<NSLayoutConstraint:0x6000021794a0 'UIView-Encapsulated-Layout-Height' UIView:0x105145820.height == 1   (active)>"
> )
> 
> Will attempt to recover by breaking constraint 
> <SnapKit.LayoutConstraint:0x600002638e40@RepositoryViewCell.swift#77 UIStackView:0x105145670.bottom == UIView:0x105145820.bottom - 12.0>
> ```
> 
> ランタイムでconsole見てみると、制約が壊れているかも

@tosh7
対応しました！[e3c760b](https://github.com/hamadayuuki/zozo-ios-engineer-codecheck/pull/9/commits/e3c760bfcf193d71bd15c7bd1dc9b76b99beaecb)
Auto Layout の競合が発生したため、ワーニング対象であるstackviewの垂直方向レイアウトの優先度を下げて (priority(.low)) 、競合を解決しました

2025-05-07 10:38 UTC, pirosix approved these changes
特に指摘する部分はなさそうです！

2025-05-09 03:37 UTC, tosh7 approved these changes

2025-05-09 07:34 UTC, merged